### ISSUE TITLE
Energy Update in 2 separate files

### ISSUE THREAD

**Issue by tuofeichen** [tuofeichen/SmartTree-Electrical#1]
Hey Kevin, 
Can you take a look at the `TFT.cpp` and `transmitter.h`, specifically as follows:
https://github.com/tuofeichen/SmartTree-Electrical/blob/master/SmartTree_Server/TFT.cpp#L62-L80
and 
https://github.com/tuofeichen/SmartTree-Electrical/blob/master/SmartTree_Server/transmitter.h#L80-L85

Are one of them redundant? 

Thanks

Best
Francis

**Comment by kevintian18** [comment]
UpdateScreenValues is the desired function to update the energy values. It seems that the only place UpdateEnergyValue is called is in transmitLogData, which is not desireable because the interval at which the energy is updated can become unpredictable. Assuming the logged data doesn't have to be the most recent data available, I would suggest getting rid of updateEnergyValue, along with its call inside transmitLogData.
Before deleting anything, however, try placing a Serial.print() inside both functions, and see the pattern of how they're called. Go ahead and delete it if the results match my reasoning.

**Comment by tuofeichen** [comment]
Sounds reasonable to me.  Closed
